### ISSUE TITLE
Plot the time period spanned by each of our gages

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#133]
Plot the time period spanned by each of our gages to see if we're currently biased to a particular time period
Envisioning a graphic like the coverage plot in the targets-3 training (3_visualize step).

**Comment by slevin75** [comment]
ok - this is what I have so far.  There is a huge drop off in gages in the mid 1980s which is very interesting.  Since we have so many gages, should I group these in some way - by state or cluster id, or something?

![image](https://user-images.githubusercontent.com/18313247/193050236-07c0f198-c956-49aa-9d19-bcc5df9fdca7.png)
![image](https://user-images.githubusercontent.com/18313247/193052237-6edcadb2-d5e5-47d0-bed5-4649df56a965.png)

**Comment by slevin75** [comment]
OK - how about this?

![image](https://user-images.githubusercontent.com/18313247/193057786-9381b0ae-7297-46a4-812c-361999ad38cb.png)
![image](https://user-images.githubusercontent.com/18313247/193057842-ef256242-f03d-4cd6-b713-c26968127084.png)

**Comment by slevin75** [comment]
Hey - I re-opened this issue because I can't remember if we resolved what we want to do with the estimated data.  I remade the plots using the estimated data only lower than the median.  There are 1444 gages using this rule and I've put the plots below, you can compare them to the plots above without any estimated data.  

I am not sure if we decided to keep all of the estimated data or just the low estimated data? Anyway, if there was a decision on that, let me know and I can put a pr in for this.

![image](https://user-images.githubusercontent.com/18313247/197220600-287dddd8-09d6-467a-9168-f7af8959c146.png)

**Comment by jds485** [comment]
Thanks! Is this plot showing colors only for complete years? Or is this still by day?

**Comment by slevin75** [comment]
This plot is complete years

**Comment by jds485** [comment]
Okay, do you also have plots when all estimated data are included? There are plots in [this comment](https://github.com/USGS-R/regional-hydrologic-forcings-ml/pull/147#issuecomment-1270100297) that are by day instead of binary complete year or not. But looking at those plots suggests that we gain quite a lot more from including estimated data > median and I'd suggest that we include all estimated data

**Comment by slevin75** [comment]
I don't have these new plots using all the estimated data but yes, we will gain a ton of data later in the period.  OK, I will make those changes and put a pr in.  Looks like tallgrass is very busy today and I am taking off early today, so it might not get done until Monday.

**Comment by jds485** [comment]
I might be misremembering, but didn't you already make a PR for which all estimated data was included?

**Comment by slevin75** [comment]
oh  - you are right.  huh.  I don't remember merging that.

**Comment by slevin75** [comment]
actually - I don't think I did have a pr for it yet.  I made a new branch and have been running it in a separate tallgrass directory but I don't think I ever put in a pr for it because we were still trying to figure out if we were going to use all the estimated data or just those under the median. If I did put in a pr, I can't seem to find it, lol

**Comment by jds485** [comment]
Okay, sounds good! If you put that branch into a PR, I can probably review later today. I think you already have the computation complete, so might just be a data transfer is needed from your fork to main
