### ISSUE TITLE
Check if removing peak flows adds sites

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#32]
To test, could edit `p1_sites_list` to include all GAGESII sites, and edit the `has_data_check` function to return all `site_nums`. To compare to using only GAGESII data with peak flows, might be best to use a function argument like `return_sites = TRUE`, and an `ifelse(return_sites, site_nums, sites_with_data)` for what to return.

**Comment by cstillwellusgs** [comment]
In GagesII there are 8 sites (out of 2,273) that do not contain peak flow data but do contain daily flows. I don't want to actually submit a pull request since the code edits should not be integrated... not sure of the best workflow on how to share. I could just show it during our meeting Monday, or I can email you a summary, or submit a pull request that you check but we never merge. Let me know.

**Comment by jds485** [comment]
Good question. I like the last suggestion of submitting a PR that we close and don't merge. That way we can still link the PR to this issue and have documentation of how it was addressed.
