### ISSUE TITLE
Create long-term average land cover features from SOHL and NLCD datasets

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#61]
Because we're working with long-term average flow statistics, I think it also makes sense to work with a single set of long-term average land cover data as features. The SOHL historical land cover years and NLCD years cover the range of years in our flow dataset, so an average should work well. Using an average will significantly reduce the number of land cover features from ~200 to 16.

SOHL data cover 1940 - 1990 in 10 year increments
NLCD data cover 2001 - 2019 in 3 year increments. To be consistent with SOHL, we can use 2001, 2011, and 2019 for an approximate decadal timeseries.

Steps:
- [ ] Create a single classification scheme (e.g., apply the NLCD land cover classes to SOHL classes)
- [ ] Average the land cover proportions for years 1940, 1950, 1960, 1970, 1980, 1990, 2001, 2011, and 2019. Could use a weighted average for each site where the weights assigned to each decade are based on the water years used for that site.

**Comment by cstillwellusgs** [comment]
Note to self - include functions for impervious cover averages (buffers and total) as well.

**Comment by cstillwellusgs** [comment]
Note to self - only 2011 NLCD data included in 'p1_sb_data_g2_csv' (CAT/ACC/TOT and with/without 50m riparian buffer). No other years in the dataset. 

What about impervious percentages by year? Check as well.

**Comment by cstillwellusgs** [comment]
Consider combining SOHL and NLCD (2001 and 2011) - would require reclassification of land covers. 

https://www.usgs.gov/special-topics/land-use-land-cover-modeling/land-cover-modeling-methodology-fore-sce-model

Refer to PUMP table from Delaware project: https://github.com/USGS-R/drb-inland-salinity-ml/blob/main/1_fetch/in/Legend_FORESCE_Land_Cover.csv, https://github.com/USGS-R/drb-inland-salinity-ml/blob/main/1_fetch/in/Legend_NLCD_Land_Cover.csv.

**Comment by cstillwellusgs** [comment]
Notes so far for @jds485 (and potentially @ajsekell):

- The FORESCE (SOHL) land cover dataset includes classes 18 & 19 (Woody Wetlands and Herbaceous Wetlands, respectively); however, these classes are not included in our SB pull (https://www.sciencebase.gov/catalog/item/58cbeef2e4b0849ce97dcd61). Maybe these land cover classes only exist in the forecasted land cover model and not the backcast? The consequence is that our reclassified land cover values have no wetlands (new class 9) for the 1940-1990 data but then they exist starting in 2001 (NLCD). Minor issue in most watersheds, but an inconsistency nonetheless. (Approx. 500 COMIDs have >5% Wetlands starting in 2001). 
- There are a handful of COMIDs with non-zero values for NLCD class 12 (Perennial Ice/Snow) and there is no equivalent class in the SOHL dataset. NLCD class 12 is reclassified to NA for our purposes. Similar to the above issue, this means that some watersheds suddenly have data in the new NA class starting in 2001. (Approx. 50 COMIDs have >1% Perennial Ice/Snow starting in 2001). 
- The following COMIDs do not have land covers that sum to 100% (+/- 1% for rounding): 817165, 4287975, 4288013, 4288603, 4289553, 4289887, 4593223, 4792494, 14156742, 22900496. I will try to investigate these COMIDs with Andrew to see what is going on. 
- Lastly, at first glance, it does seem like some sites have drastic changes in land covers after the reclassification. I'm trying to figure out a way to quickly investigate across sites where there are drastic changes from the 1990 to 2001, which would suggest that the reclassification procedure could be improved (or, maybe this is the best we can get). Will keep in touch.

**Comment by jds485** [comment]
Thanks for the update!

> wetlands classes not included in FORESCE

Those classes are included in the more recent decadal FORESCE product we're using for PUMP. Strange that they wouldn't be in this product, too. We could reclassify as water as a quick fix.

> COMIDs with non-zero values for NLCD class 12 (Perennial Ice/Snow)

That's okay to classify as NA given the low percent coverage

> COMIDs do not have land covers that sum to 100% (+/- 1% for rounding)

We saw this in PUMP for NLCD for some COMIDs. Is this for NLCD?

> reclassification

Did you use the PUMP reclassification table or a different method? Curious what you find here because one of our next steps is comparing the 2000 FORESCE and 2001 NLCD datasets

**Comment by ajsekell** [comment]
Strange that the Sohl datset isn't including the wetlands classes. I'll have a look.

But on that note, I would not use both the Sohl and NLCD land cover datasets together, at least in terms of making direct comparisons or "continuing the timeline." I was not aware that we were doing that right now.

I think it's okay to use the mining class from Sohl since that's not a class in NLCD.

The different methods and the 250 m resolution for Sohl vs 30 m for NLCD are why there are drastic changes between the two from 1990 to 2001. Technically, you're not even supposed to compare between different releases of NLCD products (though the differences are much smaller).

Andrew Sekellick
Physical Scientist
USGS MD-DE-DC Water Science Center
443-498-5580
***@***.******@***.***>

________________________________
From: Charles Stillwell ***@***.***>
Sent: Friday, April 22, 2022 4:10 PM
To: USGS-R/regional-hydrologic-forcings-ml ***@***.***>
Cc: Sekellick, Andrew J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [USGS-R/regional-hydrologic-forcings-ml] Create long-term average land cover features from SOHL and NLCD datasets (Issue #61)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Notes so far for @jds485<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjds485&data=05%7C01%7Cajsekell%40usgs.gov%7C1e0d6f498a604decb43908da249c27de%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637862550344576505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q2ku21qDIVL9VMGFJo%2F81e1rRVWuSh23VlEVW3nL%2BwI%3D&reserved=0> (and potentially @ajsekell<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fajsekell&data=05%7C01%7Cajsekell%40usgs.gov%7C1e0d6f498a604decb43908da249c27de%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637862550344576505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PDYek3uBDHjAG%2By8IzK5bbUYgyfsDk%2B%2F6kFGCtbUUWI%3D&reserved=0>):

  *   The FORESCE (SOHL) land cover dataset includes classes 18 & 19 (Woody Wetlands and Herbaceous Wetlands, respectively); however, these classes are not included in our SB pull (https://www.sciencebase.gov/catalog/item/58cbeef2e4b0849ce97dcd61<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.sciencebase.gov%2Fcatalog%2Fitem%2F58cbeef2e4b0849ce97dcd61&data=05%7C01%7Cajsekell%40usgs.gov%7C1e0d6f498a604decb43908da249c27de%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637862550344576505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b%2B68Z%2FUnfOtd7ZKnfzDlulTZHk8K8EVkG%2B8%2FYKd7NcI%3D&reserved=0>). Maybe these land cover classes only exist in the forecasted land cover model and not the backcast? The consequence is that our reclassified land cover values have no wetlands (new class 9) for the 1940-1990 data but then they exist starting in 2001 (NLCD). Minor issue in most watersheds, but an inconsistency nonetheless. (Approx. 500 COMIDs have >5% Wetlands starting in 2001).
  *   There are a handful of COMIDs with non-zero values for NLCD class 12 (Perennial Ice/Snow) and there is no equivalent class in the SOHL dataset. NLCD class 12 is reclassified to NA for our purposes. Similar to the above issue, this means that some watersheds suddenly have data in the new NA class starting in 2001. (Approx. 50 COMIDs have >1% Perennial Ice/Snow starting in 2001).
  *   The following COMIDs do not have land covers that sum to 100% (+/- 1% for rounding): 817165, 4287975, 4288013, 4288603, 4289553, 4289887, 4593223, 4792494, 14156742, 22900496. I will try to investigate these COMIDs with Andrew to see what is going on.
  *   Lastly, at first glance, it does seem like some sites have drastic changes in land covers after the reclassification. I'm trying to figure out a way to quickly investigate across sites where there are drastic changes from the 1990 to 2001, which would suggest that the reclassification procedure could be improved (or, maybe this is the best we can get). Will keep in touch.

**Comment by jds485** [comment]
Okay, in that case we can create a set of averages for the reclassified SOHL data and NLCD data separately. They can still be weighted based on the water years, but that can get complicated if a site has no data pre-2000 / post 2000. For now, I suggest we use a simple average and revisit weighting later. How does that sound?

**Comment by cstillwellusgs** [comment]
Per our discussion today, I will add the year 2000 from this dataset (https://www.sciencebase.gov/catalog/item/58cbeef2e4b0849ce97dcd61) to the 1940-1990 decadal datasets from here (https://www.sciencebase.gov/catalog/item/5a5406bee4b01e7be2308855). These data have the same resolution and land cover classes. Still need a better solution for capturing the entire period of record, to be handled later in the project.

**Comment by cstillwellusgs** [comment]
All of the COMIDs without full land cover data (sum of classes in a given year falls short of 100%) have upstream area outside of CONUS (in the ten cases here, all in Canada). @jds485 how do you think we should handle these sites? I think the easiest solution is to drop these sites since our data are incomplete, but there may be a lot of these types of sites if/when we get to CONUS-wide predictions.
